name: navigation
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  search_presentation:
        path: ../search/presentation
  wallet_presentation:
    path: ../wallet/presentation
  ComposableWidget:
    path: ../../core/composable-widget

  go_router: ^14.3.0


flutter:
  uses-material-design: true

